name: mm-exporter
port: 8081
endpoint: /metrics
metrics:
  - name: mm_rooms
    help: The count of rooms
    type: gauge
    executions:
    - type: sh
      command: docker exec -t mm /opt/multiparty-meeting/server/connect.js --stats | grep 'rooms' | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | sed -E 's/rooms:([0-9]+)/\1/g'|sed -e 's/[\r\n]//g'
      timeout: 5000
  - name: mm_peers
    help: The count of peers
    type: gauge
    executions:
      - type: sh
        command: docker exec -t mm /opt/multiparty-meeting/server/connect.js --stats | grep 'peers' | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | sed -E 's/peers:([0-9]+)/\1/g'|sed -e 's/[\r\n]//g'
        timeout: 5000
  - name: mm_cpu_usage
    help: CPU usage
    type: gauge
    executions:
      - type: sh
        command: top -bn 1 | grep -i '^CPU' | sed 's/%//g'  | awk '{print (100.0-$8)/100 }'
        timeout: 5000